import ProductCategories from '@/components/products/ProductCategories'
import ProductItems from '@/components/products/ProductItems'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import cardOne from 'assets/card-1.png'
import cardTwo from 'assets/card-2.png'
import cardThree from 'assets/card-3.png'
import { useSelector } from 'react-redux'
import { useRouter } from 'next/router'

export default function Home() {
  const [products, setProducts] = useState([]);
  const { searchText, selectedCategory } = useSelector(state => state.globals);


  useEffect(() => {
    if (selectedCategory) {
      fetch(`/api/products/${selectedCategory}`).then(data => data.json()).then(data => setProducts(data));
    } else if (searchText) {
      fetch(`/api/products/search/${searchText}`).then(data => data.json()).then(data => setProducts(data));
    } else {
      fetch('/api/products').then(data => data.json()).then(data => setProducts(data));
    }

  }, [selectedCategory, searchText])





  return (
    <>
      <Head>
        <title>Case App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='general-title'>
        <h1 className='general-title__wrapper container'>
          ÇiçekSepeti H1
        </h1>
      </div>

      <div className='breadcrumbs container'>
        <Link href='/' className='breadcrumbs-item'>
          Çiçeksepeti Market
        </Link>

        <Link href='/' className='breadcrumbs-item'>
          İstanbul
        </Link>

        <Link href='/' className='breadcrumbs-item active'>
          ÇiçeksepetiBreadCrumb
        </Link>

      </div>

      <div className='products'>
        <ProductCategories />

        <ProductItems datas={products} />
      </div>

      <div className='cards'>
        <div className='cards__wrapper container'>
          <div className='cards__item'>
            <div className='cards__item-image'>
              <Image src={cardOne} alt="Card" width={167} height={133} />
            </div>
            <div className='cards__item-content'>
              <div className='cards__item-text'>
                75 TL Üzerine Teslimat Ücreti Bizden
              </div>
              <div className='cards__item-btn'>
                <button>Detaylı Bilgi</button>
              </div>
            </div>
          </div>
          <div className='cards__item'>
            <div className='cards__item-image'>
              <Image src={cardTwo} alt="Card" width={167} height={133} />
            </div>
            <div className='cards__item-content'>
              <div className='cards__item-text'>
                Hediye Kategorisi için Sepette %15 indirim
              </div>
              <div className='cards__item-btn'>
                <button>Hediye Ürünleri</button>
              </div>
            </div>
          </div>
          <div className='cards__item'>
            <div className='cards__item-image'>
              <Image src={cardThree} alt="Card" width={167} height={133} />
            </div>
            <div className='cards__item-content'>
              <div className='cards__item-text'>
                Kırtasiye Kategorisi için Sepette %15 indirim
              </div>
              <div className='cards__item-btn'>
                <button>Detaylı Bilgi</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
